// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKmg4H7yaizxJK8aWW2wqFGA-iTnT56s',
    appId: '1:660497517730:web:601780f35bb39a0ec91bfb',
    messagingSenderId: '660497517730',
    projectId: 'smokelog-17303',
    authDomain: 'smokelog-17303.firebaseapp.com',
    storageBucket: 'smokelog-17303.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNDi4cZWPXDWfSmjIcJdAgU7xRa9sIpbE',
    appId: '1:660497517730:android:f8f78923e0a271d2c91bfb',
    messagingSenderId: '660497517730',
    projectId: 'smokelog-17303',
    storageBucket: 'smokelog-17303.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7tA65_rkd7G-Kmh_NZAsj3Y5N81YcPHY',
    appId: '1:660497517730:ios:ec672c856d4780a2c91bfb',
    messagingSenderId: '660497517730',
    projectId: 'smokelog-17303',
    storageBucket: 'smokelog-17303.firebasestorage.app',
    iosClientId: '660497517730-an04u70e9dfg71meco3ev6gvcri684hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.smokeLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSc89SEMjq4XD3HluQX06OJoGmjzZpg3I',
    appId: '1:660497517730:web:552ee2054f59d910c91bfb',
    messagingSenderId: '660497517730',
    projectId: 'smokelog-17303',
    authDomain: 'smokelog-17303.firebaseapp.com',
    storageBucket: 'smokelog-17303.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7tA65_rkd7G-Kmh_NZAsj3Y5N81YcPHY',
    appId: '1:660497517730:ios:ec672c856d4780a2c91bfb',
    messagingSenderId: '660497517730',
    projectId: 'smokelog-17303',
    storageBucket: 'smokelog-17303.firebasestorage.app',
    iosClientId: '660497517730-an04u70e9dfg71meco3ev6gvcri684hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.smokeLog',
  );

}